### PR TITLE
Initial design

### PR DESCRIPTION
**Pull request by apeksharma**
Signed-off-by: Apekshit Sharma <apekshit.sharma@hedera.com>

### CODE REVIEW

**Review by medvedev1088 — APPROVED** [review]
LGTM. 

I have a few questions regarding the design:

1. The reason we don't use the TIMESTAMP type for consensusTimestamp is we need nanoseconds resolution, which is not supported by BigQuery's TIMESTAMP? An alternative option would be to have 2 fields: consensusTimestamp and consensusTimestampTruncated, the latter one is truncated to microseconds and has type TIMESTAMP. The table is partitioned by consensusTimestampTruncated. This way it might be more convenient for users to view the data in Preview, write queries with timestamp filter etc. The downside is having 2 fields instead of 1 may be confusing without explanation.
2. Are the stream files in GCS or S3?
3. How are new stream files in GCS/S3 discovered? Via polling or e.g. Pub/Sub notifications https://cloud.google.com/storage/docs/pubsub-notifications or S3 event notifications?
4. Where will the "Hedera Mirror Importer" be deployed? The options I see are GKE, Dataflow, a pure VM. Dataflow would fit nicely if  GCS Pub/Sub notifications are used, and it can scale automatically (not sure autoscaling is needed here).
5. Where will deduplication run? A few options I see are BigQuery scheduled queries https://cloud.google.com/bigquery/docs/scheduling-queries. Really simple to setup but the maximum frequency is 1 hour and not sure it handles transient errors. Another option is Cloud Composer - it's gonna be more expensive but more flexible as retry logic can be configured.

**Comment by apeksharma** [comment]
> 1. The reason we don't use the TIMESTAMP type for consensusTimestamp is we need nanoseconds resolution, which is not supported by BigQuery's TIMESTAMP? An alternative option would be to have 2 fields: consensusTimestamp and consensusTimestampTruncated, the latter one is truncated to microseconds and has type TIMESTAMP. The table is partitioned by consensusTimestampTruncated. This way it might be more convenient for users to view the data in Preview, write queries with timestamp filter etc. The downside is having 2 fields instead of 1 may be confusing without explanation.

You're right, nanoseconds resolution is the reason. Am okay with extra column, however wouldn't partitioning by consensusTimestampTruncated make certain queries more cumbersome?
For e.g. to do point or range lookup by consensusTimestamp, one would also need to add condition on  consensusTimestampTruncated to avoid full table scan.

> 2. Are the stream files in GCS or S3?

Both.

> 3. How are new stream files in GCS/S3 discovered? Via polling or e.g. Pub/Sub notifications https://cloud.google.com/storage/docs/pubsub-notifications or S3 event notifications?

Polling. No upcoming plans to switch them to notifications either. :(

> 4. Where will the "Hedera Mirror Importer" be deployed? The options I see are GKE, Dataflow, a pure VM. Dataflow would fit nicely if  GCS Pub/Sub notifications are used, and it can scale automatically (not sure autoscaling is needed here).

Mirror node has helm charts (recent addition) so we are thinking about GKE, otherwise VM. Those two are preferred options for hedera-mirror-importer since 5+ other similar stacks are in VM right now and plan is to move them to GKE in coming months.

> 5. Where will deduplication run? A few options I see are BigQuery scheduled queries https://cloud.google.com/bigquery/docs/scheduling-queries. Really simple to setup but the maximum frequency is 1 hour and not sure it handles transient errors. Another option is Cloud Composer - it's gonna be more expensive but more flexible as retry logic can be configured.

Yes, 1 hour seems too much. Can explore Cloud Composer, or cron job in GKE.

**Comment by medvedev1088** [comment]
> For e.g. to do point or range lookup by consensusTimestamp, one would also need to add condition on consensusTimestampTruncated to avoid full table scan.

That's a good point. Using consensusTimestampTruncated would make sense with the assumption that most queries won't need nanosecond resolution for the timestamp. If it's not the case then the original schema is better.

**Comment by apeksharma** [comment]
> That's a good point. Using consensusTimestampTruncated would make sense with the assumption that most queries won't need nanosecond resolution for the timestamp. If it's not the case then the original schema is better.

Hard to say what most queries will do at this point. I guess we can just add it and see how it goes.

**Pull request merged**
